apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-cronjob
spec:
  schedule: "* * * * *" # Every minute
  jobTemplate:
    spec:
      completions: 5
      parallelism: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: echo
            image: busybox
            command: ["echo", "Triggered by a CronJob"] # Check for logs of pod to see the output kubectl logs pod <pod-name>
