apiVersion: v1
kind: Namespace
metadata:
  name: ubuntu

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep1
  name: dep1
  namespace: ubuntu
spec:
  selector:
    matchLabels:
      app: dep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep1
    spec:
      containers:
      - args:
        - sleep
        - "10000"
        image: ubuntu
        name: ubuntu
        resources: 
         limits:
           memory: 800Mi
           cpu: 100m
         requests: 
           memory: 150Mi
           cpu: 40m
status: {}
