apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
 name: ubuntu-hpa
 namespace: ubuntu
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: dep1
 minReplicas: 2
 maxReplicas: 5
 metrics:
 - type: Resource
   resource:
     name: cpu
     targetAverageUtilization: 20
 - type: Resource
   resource:
     name: memory
     targetAverageUtilization: 20
